### PR TITLE
Add troubleshooting steps in README for dnsmasq

### PR DESCRIPTION
**Pull request by voidanix**

### CODE REVIEW

**Comment by rinigus** [comment]
I have never seen this issue. @piggz - do you know anything about it?

**Comment by piggz** [comment]
Ive been having similar issues, but didnt know about this fix.  It seems that since i updated to 4.3, i had container-starting issues.  My work around so far has been to stop the container, killall dnsmasq and start the container.

I wonder if its because the dnsmasq systemd service is running, and the manual start of dnsmasq from waydroid then fails ?

**Comment by voidanix** [comment]
This is my first time interacting with Waydroid and only got the chance to test this on 4.3.0 indeed.

> My work around so far has been to stop the container, killall dnsmasq and start the container.

What do you exactly mean with "stop the container"? The container itself is not really active unless you start a session (`waydroid-container.service` being active at the beginning seems to only wait for a session to get started).

Once `waydroid session start` must kick in, the container service fails after the typical *waiting 10 seconds for the container to start*.

I have not thought of killing dnsmasq as the service was enabled at boot.

**Comment by piggz** [comment]
I dont think the service should be enabled at all...im not sure how it got enabled.  Would you do some testing after performing
systemctl disable dnsmasq?

**Comment by voidanix** [comment]
Indeed everything is fine without the dnsmasq service enabled, after rebooting Waydroid start the program itself.

Could it be that because it is a dependency, after installation it got automatically enabled?

**Comment by piggz** [comment]
Im not sure, but perhaps you could change the PR to describe disabling the service?

**Pull request merged**
